apiVersion: v1
kind: Namespace
metadata:
  name: chatback
  labels:
    name: chatback

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db
  namespace: chatback
  labels:
    app: chatback
    tier: db
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
      - name: db
        image: chatback-db
        imagePullPolicy: Never
        ports:
          - name: cb-db
            containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: password

---

apiVersion: v1
kind: Service
metadata:
  namespace: chatback
  name: db
spec:
  selector:
    tier: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: broker
  namespace: chatback
  labels:
    app: chatback
    tier: broker
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: broker
  template:
    metadata:
      labels:
        tier: broker
    spec:
      containers:
      - name: broker
        image: chatback-broker
        imagePullPolicy: Never
        ports:
          - name: cb-broker
            containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  namespace: chatback
  name: broker
spec:
  selector:
    tier: broker
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  namespace: chatback
  labels:
    app: chatback
    tier: backend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: backend
        image: chatback-server
        imagePullPolicy: Never
        ports:
          - name: cb-backend
            containerPort: 8080
        env:
        - name: DB_HOST
          value: db
        - name: BROKER_URI
          value: http://broker:50051

---

apiVersion: v1
kind: Service
metadata:
  namespace: chatback
  name: backend
spec:
  selector:
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: chatback
  labels:
    app: chatback
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: chatback-client
        imagePullPolicy: Never
        ports:
          - name: cb-fontend
            containerPort: 80
        env:
        - name: SERVER_URI
          value: "http://backend:8080"

---

apiVersion: v1
kind: Service
metadata:
  namespace: chatback
  name: frontend
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer