version: '3'

services:

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - cb_network
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - cb_network
    environment:
      - SERVER_URI="http://backend:8080"
    ports:
      - "3000:80"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=password
    networks: 
      - cb_network
    ports:
      - "5432:5432"

networks:
  cb_network: