apiVersion : apps/v1
kind: Deployment
metadata:
  name: broker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker 
    spec:
      containers:
        - name: broker 
          image: srich.azurecr.io/broker
          ports:
          - containerPort: 50051