output   = "models"
wipe     = true
no-tests = true

[psql]
  dbname = "postgres"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "password"
  schema = "public"
  sslmode = "disable"
  blacklist = ["migrations", "other"]